### ISSUE TITLE
Python 3.11 - re.error: global flags not at the start of the expression at position 1

### ISSUE THREAD

**Issue by vivasconcelos** [ixmatus/inflector#12]
Steps to reproduce:

1. Install python 3.11
2. Run on python interpreter:
```
>>> import inflector
>>> infl = inflector.Inflector()
>>> name = "movie"
>>> infl.pluralize(name)
```

**Comment by ixmatus** [comment]
Thanks for the issue report! I'm not actively maintaining this project and haven't for a while, PRs are welcome though and I'm happy to merge them (or even give the commit bit) and publish to PyPi.

**Comment by vEpiphyte** [comment]
@ixmatus With yukihiko's fix, can this be released on pypi in order to add 3.11 support?

**Comment by ixmatus** [comment]
Yep, I can release it. Thanks for saying something!

**Comment by ixmatus** [comment]
@vEpiphyte https://pypi.org/manage/project/Inflector/release/3.1.0/. Sorry for the delay!
