### ISSUE TITLE
Python3.12 release

### ISSUE THREAD

**Issue by billy-doyle** [ixmatus/inflector#15]
As @paulcwatts noted in https://github.com/ixmatus/inflector/pull/14#issuecomment-1836618885, no release went out for python 3.12 support in https://github.com/ixmatus/inflector/pull/14.

@ixmatus can you release?

**Comment by ixmatus** [comment]
I'll try to get to it tomorrow!

**Comment by ixmatus** [comment]
This is now done: https://pypi.org/project/Inflector/3.1.1/.

**Comment by billy-doyle** [comment]
Thanks @ixmatus 🚀
