### ISSUE TITLE
Pluralize verbs.

### ISSUE THREAD

**Issue by proofit404** [ixmatus/inflector#7]
Hello, thanks for awesome library.

I have a little trouble with it. I expect that `pluralize('is')` will evaluates to `'are'` and `pluralize('was')` will evaluates to `'were'`. Is it possible to fix? If this require complex change can you explain necessary steps so I can make a pull request?

Regards, Artem.

**Comment by ixmatus** [comment]
To be honest, I yanked this lib from somewhere that wasn't hosting it on
source control (I think it was a forum post or something?) and this was
like six or seven years ago. I no longer even program in Python
professionally.

If you'd like to contribute your fixes in a PR, I will accept it, but I'm
no longer accepting social responsibility for this project. If you are
willing to become a maintainer I'd be happy to transfer contributor rights
to you.

On Sun, Mar 13, 2016 at 4:42 PM, Malyshev Artem <notifications@github.com>
wrote:

> Hello, thanks for awesome library.
>
> I have a little trouble with it. I expect that pluralize('is') will
> evaluates to 'are' and pluralize('was') will evaluates to 'were'. Is it
> possible to fix? If this require complex change can you explain necessary
> steps so I can make a pull request?
>
> Regards, Artem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ixmatus/inflector/issues/7>.
>



-- 
Parnell Springmeyer
parnell@digitalmentat.com | digitalmentat.com | 0xDCCF89258EAD874A
<http://pgp.mit.edu/pks/lookup?op=get&search=0xDCCF89258EAD874A>

**Comment by ixmatus** [comment]
Oh, to answer your question, I don't know where you would make that change.
I didn't write the lib, but it should be fairly simple I think.

On Sun, Mar 13, 2016 at 5:32 PM, Parnell Springmeyer <
parnell@digitalmentat.com> wrote:

> To be honest, I yanked this lib from somewhere that wasn't hosting it on
> source control (I think it was a forum post or something?) and this was
> like six or seven years ago. I no longer even program in Python
> professionally.
>
> If you'd like to contribute your fixes in a PR, I will accept it, but I'm
> no longer accepting social responsibility for this project. If you are
> willing to become a maintainer I'd be happy to transfer contributor rights
> to you.
>
> On Sun, Mar 13, 2016 at 4:42 PM, Malyshev Artem <notifications@github.com>
> wrote:
>
>> Hello, thanks for awesome library.
>>
>> I have a little trouble with it. I expect that pluralize('is') will
>> evaluates to 'are' and pluralize('was') will evaluates to 'were'. Is it
>> possible to fix? If this require complex change can you explain necessary
>> steps so I can make a pull request?
>>
>> Regards, Artem.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ixmatus/inflector/issues/7>.
>>
>
>
>
> --
> Parnell Springmeyer
> parnell@digitalmentat.com | digitalmentat.com | 0xDCCF89258EAD874A
> <http://pgp.mit.edu/pks/lookup?op=get&search=0xDCCF89258EAD874A>
>



-- 
Parnell Springmeyer
parnell@digitalmentat.com | digitalmentat.com | 0xDCCF89258EAD874A
<http://pgp.mit.edu/pks/lookup?op=get&search=0xDCCF89258EAD874A>

**Comment by proofit404** [comment]
I will try to hack on it. If it will successful it is possible that I will came up with decision to became a library maintainer. But let see if I can do this first.

**Comment by ixmatus** [comment]
Closing as I'm not actively maintaining this project (however, I will accept PRs and strongly encourage anyone who wants to become a maintainer, I'll hand the commit bit over).
