### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by travis-cramer** [ixmatus/inflector#8]
Hello. This is a wonderful package. We use it all the time. Is it Python 3 compatible? Thank you.

**Comment by ixmatus** [comment]
@travis-cramer thanks for the issue. I only keep this package on life-support and I haven't done any work to make it Python 3 compatible. If I find some time I will try to do that, otherwise if you do that work please submit a PR so other people can benefit!

**Comment by zhammer** [comment]
Awesome to see python3 support added in #9! Will you be putting out a pypi release soon?

**Comment by ixmatus** [comment]
Done https://pypi.org/manage/project/Inflector/release/3.0.0/

**Comment by zhammer** [comment]
awesome :)
